/*
    Cyber Risk Analysis Module (Educational Prototype)

    This program represents a consultative risk assessment tool designed for
 educational purposes within a school cybersecurity context.

    The module analyzes reported cybersecurity incidents, evaluates their risk
 level based on predefined criteria, and suggests appropriate preventive
 measures. In addition, it provides a summary of risk levels across different
 school zones and highlights areas with increased risk based on historical
 incident patterns.

    The results generated by this program are advisory in nature and are intended
 to support awareness, prevention, and decision-making processes. The system
 does not perform real-time threat detection and does not guarantee the
 prediction of future cyber attacks.

The input must be done in id increasing (sorted) order in order for the binary search to work.

Input using the structure Zone ID, Zone Name, Severity, Severity Multiplier, Number of Attacks ( Low, Medium, High risk ).

*/

#include <fstream> // Used for the data history
#include <iostream> // Used for reporting an incident
#include <climits>
#include <algorithm> // For binary search

using namespace std;

ifstream fin("zone.in");
ofstream fout("output.out");

float MultiplierLow = 1, MultiplierMedium = 1.25, MultiplierHigh = 1.5; // Multipliers - based on the incident type, decided by the user - change if needed
int HighLimit = 500, MediumLimit = 250; // Score limits - change if needed

int ZoneId, AttackId, IncidentId; // Declaration of input vars
float Severity;
string ZoneName, AttackName, AttackImpact;


struct zone {
    int ID;
    float Severity;
    string ZoneName;
    int Low, Medium, High;
    char MostLikely;
    float Multiplier;
};

char CheckRisk(float a, float b, float c) {
    float maxi = max( a, max(b, c) );
    if (maxi == c)
        return 'H';
    if (maxi == b)
        return 'M';
    if (maxi == a)
        return 'L';

    return 'H'; // Fallback
}

char identifytype(string a) {
    if (a == "LOW")
        return 'L';
    if (a == "MED")
        return 'M';
    if (a == "HIGH")
        return 'H';
    return 'H';
}

void displayrisk(zone a) {
    char result = CheckRisk(a.Low, a.Medium, a.High);
    if (result == 'H')
        cout << "Most attack were of HIGH RISK.";
    else if (result == 'M')
        cout << "Most attacks were of MEDIUM RISK";
    else if (result == 'L')
        cout << "Most attacks were of LOW RISK";

    cout << '\n';

}

bool comp(const zone& a,const zone& b) {
    return a.ID < b.ID;
}

int main() {
    int n; // Number of zones
    fin >> n;
    zone v[n];
    int MaxSeverity = INT_MIN, MaxIndex = -1;

    for (int i = 0; i < n; i++) { // Read zone.in
        fin >> v[i].ID;
        fin >> v[i].ZoneName;
        fin >> v[i].Severity;
        fin >> v[i].Multiplier;
        fin >> v[i].Low;
        fin >> v[i].Medium;
        fin >> v[i].High;
        float Low = v[i].Low * MultiplierLow, Medium = v[i].Medium * MultiplierMedium , High = v[i].High * MultiplierHigh;
        v[i].MostLikely = CheckRisk(Low, Medium, High);
        if (v[i].Severity > MaxSeverity) {
            MaxSeverity = v[i].Severity;
            MaxIndex = i;
        }
    }

    cout << "The order is: Incident_ID, Zone, Severity, Attack and Attack Impact" << endl;

    cout << "Paste input? (Y/N): ";
    char tempc2;
    cin >> tempc2;

    if (tempc2 != 'N' && tempc2 != 'Y') {
        cout << "Incorrect input.";
        return 0;
    }

    if (tempc2 == 'N') {                // Input from console
        cout << "Insert IncidentId: ";
        cin >> IncidentId;
        cout << "Insert Zone: ";
        cin >> ZoneId;
        cout << "Insert Severity: ";
        cin >> Severity;
        cout << "Insert AttackId: ";
        cin >> AttackId;
        cout << "Insert Attack Impact (LOW, MED or HIGH): ";
        cin >> AttackImpact;
    }
    else {
        cin >> IncidentId;
        cin >> ZoneId;
        cin >> Severity;
        cin >> AttackId;
        cin >> AttackImpact;
    }

    char type = identifytype(AttackImpact);

        zone key;
        key.ID = ZoneId;
        auto it = lower_bound(v, v + n, key, comp);
        if (it == v + n || it->ID != ZoneId) {
            cout << "Zone not found." << endl;
            return 0;
        }
        else {
            int zoneindex = it - v;

            if (type == 'L')
                v[zoneindex].Low++;
            else if (type == 'M')
                v[zoneindex].Medium++;
            else if (type == 'H')
                v[zoneindex].High++;

            v[zoneindex].Severity += Severity * v[zoneindex].Multiplier;

            int NewIndex;
            if ( v[zoneindex].Severity < MaxSeverity ) {
                NewIndex = MaxIndex;
                cout << "The zone with the ID " << v[MaxIndex].ID << " is the most vulnerable location. Take action!" << '\n';
                displayrisk(v[MaxIndex]);

            }
            else {
                NewIndex = zoneindex;;
                cout << "This incident creates a NEW most dangerous zone (ID "
                << ZoneId << "). Take immediate action!" << '\n';
                displayrisk(v[zoneindex]);
            }
            if(v[NewIndex].Severity >= HighLimit)
                cout << "Risk Level: HIGH" << '\n';
            else
                if (v[NewIndex].Severity >= MediumLimit)
                    cout << "Risk Level: MEDIUM" << '\n';
                else
                    cout << "Risk Level: LOW" << '\n';

        }

    // Write output.out
    fout << "Summary:" << '\n';
    for (int i = 0; i < n; i++) {
        fout << v[i].ID << " ";
        fout << v[i].ZoneName << " ";
        fout << v[i].Severity << " ";
        fout << v[i].Low << " ";
        fout << v[i].Medium << " ";
        fout << v[i].High << " ";
        if(v[i].Severity >= HighLimit)
            fout << "Risk Level: HIGH" << '\n';
        else
            if (v[i].Severity >= MediumLimit)
                fout << "Risk Level: MEDIUM" << '\n';
            else
                fout << "Risk Level: LOW" << '\n';
    }


    return 0;

}
